FROM python:3.10-slim-bullseye 

ENV WORKSPACE=/workspace
ENV PYTHONPATH=$WORKSPACE/src
WORKDIR $WORKSPACE
RUN apt-get -q update && \
    apt-get install --no-install-recommends -qy libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev libharfbuzz-dev libfribidi-dev tcl8.6-dev tk8.6-dev python-tk python3-tk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY src/requirements-gui.txt /workspace/src/requirements-gui.txt
COPY src/lal_modules/requirements.txt /workspace/src/lal_modules/requirements.txt
RUN pip install -r src/requirements-gui.txt
COPY resources resources
COPY src src
RUN useradd user
USER user

ENV DISPLAY=unix:0
ENTRYPOINT ["python", "src/gui.py"]